### ISSUE TITLE
different path on other users

### ISSUE THREAD

**Issue by yogithesymbian** [kdcro101/vscode-favorites#60] opened 2021-03-23 04:32 UTC
**Describe your use case.**
i have config in vscode setting.json

```
{
    "favorites.storageFilePath": "what directory sample ? ",
    ....
    ...
```
    
### in my favorite.json
 mac users
```
    {
        "type": "Group",
        "name": "AA0002",
        "parent_id": null,
        "workspaceRoot": null,
        "workspacePath": null,
        "id": "KHrISFa6i7WhY0ub"
    },
    {
        "type": "File",
        "name": "/Users/yogiarifwidodo/Sites/sample/sampleone/js/views/sampletwo/sampletwo.vue",
        "parent_id": "KHrISFa6i7WhY0ub",
        "workspaceRoot": "/Users/yogiarifwidodo/Sites/sample",
        "workspacePath":  "/Users/yogiarifwidodo/Sites/sample/sampleone/js/views/sampletwo/sampletwo.vue",
        "id": "tnKo7UO8R4jG6rcZ"
    },
```

windows user
```
    {
        "type": "Group",
        "name": "AA0001",
        "parent_id": "nepcWL5GtbxUZJhQ",
        "workspaceRoot": null,
        "workspacePath": null,
        "id": "12rOiQ0Rga3uwjLY"
    },
    {
        "type": "File",
        "name": "c:\\project\\htdocs\\sample\\sampleone\\js\\views\\sample.vue",
        "parent_id": "3ZuPjkUOxRGm1F7w",
        "fsPath": "c:\\project\\htdocs\\sample\\sampleone\\js\\views\\sample.vue",
        "workspaceRoot": null,
        "workspacePath": null,
        "id": "FZ5R09s6S7KxTWUj"
    },
```

**Comment by halo** [comment] 2022-02-20 17:50
I think this is a duplicate of https://github.com/kdcro101/vscode-favorites/issues/48

**Comment by yogithesymbian** [comment] 2022-02-21 05:56
> ZuPjkUOxRGm1F7w",
>         "fsPath": "c:\\project\\htdocs\\sample\\sampleone\\js\\views\\sample.vue",
>         "workspaceRoot": n

yes right , i didnt see ,

**Closed as completed** 2022-02-21 05:56 UTC
